config/routes.rb
Rails.application.routes.draw do
  get 'share/new'
  root to: "blobs#index"
  devise_for :users

  resources :blobs

  post 'file/attach' => 'file#attach'
  delete 'file/delete' => 'file#delete'

  get 'share/new' => 'share#new'
  post 'share/create' => 'share#create'
  delete 'share/delete' => 'share#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shared_file_association.rb
class SharedFileAssociation < ApplicationRecord
  belongs_to :user

  def self.get_shared_files(user_id)
    SharedFileAssociation
      .joins(:user)
      .joins('INNER JOIN active_storage_attachments ON active_storage_attachments.id = shared_file_associations.file_id AND
        active_storage_attachments.record_type = "User" AND
        active_storage_attachments.record_id = shared_file_associations.user_id ')
      .joins('INNER JOIN active_storage_blobs ON active_storage_blobs.id = active_storage_attachments.blob_id')
      .where('shared_file_associations.shared_user_id = ?', user_id)
      .select('users.email, users.id as user_id, active_storage_attachments.id as file_id, active_storage_blobs.filename, active_storage_blobs.byte_size,shared_file_associations.id, shared_file_associations.created_at')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many_attached :files
  has_many :shared_file_associations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :get_url, :file_size_verbose, :get_shared_url

  def get_shared_url(user_id, file_id)
    shared_file = User.find(user_id).files.find(file_id)
    get_url(shared_file) if shared_file.present?
  end

  def get_url(blob)
    Rails.application.routes.url_helpers.rails_blob_path(blob, only_path: true)
  end

  def file_size_verbose(byte)
    @kb = byte / 1024
    if @kb < 1024
      return "#{@kb} KB"
    end
    @mb = @kb / 1024
    if @mb < 1024
      return "#{@mb} MB"
    end
    @gb = @mb / 1024
    return "#{@gb} GB"
  end
end

app/controllers/blobs_controller.rb
class BlobsController < ApplicationController
  def index
    @q = current_user.files.blobs.ransack(params[:q])
    @files = @q.result

    @shared_files = SharedFileAssociation.get_shared_files(current_user.id)
  end
end

app/controllers/file_controller.rb
class FileController < ApplicationController

  def attach
    file = params[:user][:file]
    if file.size < 10.megabytes
      if current_user.files.attach(file)
        flash[:notice] = 'File uploaded Successfully'
      else
        flash[:notice] = 'File uploading Unsuccessfull'
      end
    else
      flash[:notice] = 'File size should be less than 10 Megabyte'
    end
    redirect_to '/'
  end

  def delete
    file = current_user.files.find_by(id: params[:file])
    if file.present?
      file.purge
      current_user.shared_file_associations.where(file_id: 1).destroy_all
      flash[:notice] = 'File Deleted Successfully'
    else
      flash[:notice] = 'File Deletion Unsuccessfull'
    end
    redirect_to '/'
  end
end

app/controllers/share_controller.rb
class ShareController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    file = current_user.files.find(params[:file]) if params[:file].present?

    if user.present? && file.present? && user != current_user
      shared_file = SharedFileAssociation.find_by(user_id: current_user.id,
        shared_user_id: user.id,
        file_id: file.id
      )
      if shared_file.blank?
        shared_file = SharedFileAssociation.create(
                          user_id: current_user.id,
                          shared_user_id: user.id,
                          file_id: file.id
                        )
      end
      ShareMailer.with(user: current_user, shared_user: user,filename: file.filename.to_s, link: 'http://localhost:3000/').share_file.deliver_later

      if shared_file.errors.present?
        flash[:notice] = 'File sharing Unsuccessfull'
      else
        flash[:notice] = 'File shared Successfully'
      end
    else
      flash[:notice] = 'EmailId Invalid'
    end
    redirect_to '/'
  end

  def new
    @file = params[:file]
  end

  def delete
    shared_file = SharedFileAssociation.find_by(id: params[:file], shared_user_id: current_user.id)
    if shared_file.present?
      shared_file.destroy
      flash[:notice] = 'Shared File Deleted Successfully'
    else
      flash[:notice] = 'Shared File Deletion Unsuccessfull'
    end
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/share_helper.rb
module ShareHelper
end

app/views/blobs/index.html.erb
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h2>Uploaded File Dashboard </h2>
                    </div>
                     <div class="col-sm-4">
                        <%= search_form_for @q do |f| %>
                            <%= f.search_field :filename_cont, placeholder: 'Search' %>
                            <%= f.submit("Search")%>
                        <% end %>
                    </div>
                    <div class="col-sm-3">
                        <%= form_for(:user, url: 'file/attach') do |f| %>
                              <div class="custom-file add-new">
                                <%= f.label :file, class:"custom-file-label" do %>Upload File
                                    <%= f.file_field :file, class: 'custom-file-input', 
                                        onchange: "this.form.submit();" %>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <% if @files.present? && @files.any? %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><%= sort_link(@q, :filename) %></th>
                            <th><%= sort_link(@q, :created_at, "Uploaded At") %></th>
                            <th><%= sort_link(@q, :bytesize, "Size") %> </th>
                            <th>Actions</th>
                            <th>Sharing</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @files.each do |file| %>
                            <tr>
                                <td><%= file.filename %></td>
                                <td><%= file.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                <td><%= file_size_verbose file.byte_size %></td>
                                <td>
                                    <%= link_to 'Download', "#{get_url(file)}", download: '' %> |&nbsp;
                                    <%= link_to 'Delete', file_delete_path(file: file), :data => { :confirm => 'Are you sure?' }, method: "delete"%>
                                </td>
                                <td>
                                    <%= link_to 'Share Link', "#{get_url(file)}"%>| <%= link_to 'Send File', share_new_path(file: file)%>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            <% else %>
                <h3>No Files</h3>
            <% end %>
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-9">
                        <h2> Shared Files Dashboard</h2>
                    </div>
                </div>
            </div>
            <% if @shared_files.present? && @shared_files.any? %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Filename </th>
                            <th>Shared On </th>
                            <th>Size </th>
                            <th>Actions</th>
                            <th>Shared_by</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <% @shared_files.each do |file| %>
                            <tr>
                                <td><%= file.filename %></td>
                                <td><%= file.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                <td><%= file_size_verbose file.byte_size %></td>
                                <td>
                                    <%= link_to 'Download', get_shared_url(file.user_id, file.file_id), download: '' %> |&nbsp; 
                                    <%= link_to 'Delete', share_delete_path(file: file), :data => { :confirm => 'Are you sure?' }, method: "delete"%>
                                </td>
                                <td><%= file.email %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
             <% else %>
                <h3>No Shared Files</h3>
            <% end %>
        </div>
    </div>    

app/views/home/index.html.erb
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h2>Uploaded File Dashboard </h2>
                    </div>
                     <div class="col-sm-4">
                        <%= form_with(url: '/', method: 'get') do |f| %>
                            <%= f.text_field :hint,placeholder: 'Search' %>
                            <%= f.submit("Search")%>
                        <% end %>
                    </div>
                    <div class="col-sm-3">
                        <%= form_for(:user, url: 'file/attach') do |f| %>
                              <div class="custom-file add-new">
                                <%= f.label :file, class:"custom-file-label" do %>Upload File
                                    <%= f.file_field :file, class: 'custom-file-input', 
                                        onchange: "this.form.submit();" %>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <% if @files.any? %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><%= link_to "File Name", :sort => "name"%> </th>
                            <th><%= link_to "Uploaded Date", :sort => "created_at"%> </th>
                            <th><%= link_to "Size", :sort => "size"%> </th>
                            <th>Actions</th>
                            <th>Sharing</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @files.each do |file| %>
                            <tr>
                                <td><%= file.filename %></td>
                                <td><%= file.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                <td><%= file_size_verbose file.byte_size %></td>
                                <td>
                                    <%= link_to 'Download', "#{get_url(file)}", download: '' %> |&nbsp;
                                    <%= link_to 'Delete', file_delete_path(file: file), :data => { :confirm => 'Are you sure?' }, method: "delete"%>
                                </td>
                                <td>
                                    <%= link_to 'Share Link', "#{get_url(file)}"%>| <%= link_to 'Send File', share_new_path(file: file)%>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            <% else %>
                <h3>No Files</h3>
            <% end %>
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-9">
                        <h2> Shared Files Dashboard</h2>
                    </div>
                </div>
            </div>
            <% if @shared_files.any? %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th><%= link_to "File Name", :share_sort => "name"%> </th>
                            <th><%= link_to "Shared On", :share_sort => "created_at"%> </th>
                            <th><%= link_to "Size", :share_sort => "size"%> </th>
                            <th>Actions</th>
                            <th>Shared_by</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <% @shared_files.each do |file| %>
                            <tr>
                                <td><%= file.filename %></td>
                                <td><%= file.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                <td><%= file_size_verbose file.byte_size %></td>
                                <td>
                                    <%= link_to 'Download', get_shared_url(file.user_id, file.file_id), download: '' %> |&nbsp; 
                                    <%= link_to 'Delete', share_delete_path(file: file), :data => { :confirm => 'Are you sure?' }, method: "delete"%>
                                </td>
                                <td><%= file.email %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
             <% else %>
                <h3>No Shared Files</h3>
            <% end %>
        </div>
    </div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareFileUsingGem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/share/new.html.erb
<div class="signup-form">
    <%= form_with url: '/share/create' do |form| %>
        <h3> Send File </h3>  
        <hr>
        <div class="form-group">      
            <%= form.label :email %>
            <%= form.text_field :email,class: "form-control" %>
        </div>
        <%= form.hidden_field :file, value: @file %>
        <div class="form-group">
            <%= form.submit "Submit", class: 'btn btn-primary btn-block btn-lg' %>
        </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ShareFile</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>